#ifndef __XACT_PROJECT_NNN_SOUND__
#define __XACT_PROJECT_NNN_SOUND__

typedef enum
{
    XACT_WAVEBANK_MOVE_SOIL_HORSE_DIAMOUNT = 0,
    XACT_WAVEBANK_MOVE_SOIL_HORSE_RIDE = 1,
    XACT_WAVEBANK_MOVE_SOIL_JUMP = 2,
    XACT_WAVEBANK_MOVE_SOIL_METAL_01 = 3,
    XACT_WAVEBANK_MOVE_SOIL_METAL_02 = 4,
    XACT_WAVEBANK_MOVE_SOIL_METAL_03 = 5,
    XACT_WAVEBANK_MOVE_SOIL_METAL_04 = 6,
    XACT_WAVEBANK_MOVE_SOIL_METAL_05 = 7,
    XACT_WAVEBANK_MOVE_SOIL_METAL_06 = 8,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_DASH = 9,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_DOWN_L = 10,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_DOWN_S = 11,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_LAND_01 = 12,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_LAND_02 = 13,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_RUN_01 = 14,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_RUN_02 = 15,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_WALK_01 = 16,
    XACT_WAVEBANK_MOVE_SOIL_SOIL_WALK_02 = 17,
    XACT_WAVEBANK_MOVE_SOIL_ARMOR_RUB_01 = 18,
    XACT_WAVEBANK_MOVE_SOIL_B_GUARD = 19,
} XACT_WAVEBANK_MOVE_SOIL;

#define XACT_WAVEBANK_MOVE_SOIL_ENTRY_COUNT 20

typedef enum
{
    XACT_WAVEBANK_ATTACK_B_AT_B_SWING_L01 = 0,
    XACT_WAVEBANK_ATTACK_B_AT_B_SWING_S01 = 1,
    XACT_WAVEBANK_ATTACK_B_AT_B_SWING_S02 = 2,
    XACT_WAVEBANK_ATTACK_B_AT_B_ASFA_ORB_A = 3,
    XACT_WAVEBANK_ATTACK_B_AT_B_ASFA_ORB_C = 4,
    XACT_WAVEBANK_ATTACK_B_AT_B_ASPH_ORB_SF = 5,
    XACT_WAVEBANK_ATTACK_B_AT_B_ASFA_ORB_S = 6,
} XACT_WAVEBANK_ATTACK_B;

#define XACT_WAVEBANK_ATTACK_B_ENTRY_COUNT 7

typedef enum
{
    XACT_WAVEBANK_AMBI_CROWD_CROWD_MIDDLE_01_REV = 0,
    XACT_WAVEBANK_AMBI_CROWD_CROWD_MORE_LARGE_REV = 1,
    XACT_WAVEBANK_AMBI_CROWD_CROWD_SMALL_01_REV = 2,
    XACT_WAVEBANK_AMBI_CROWD_CROWD_BACK_REV_02 = 3,
    XACT_WAVEBANK_AMBI_CROWD_CROWD_LARGE_04_REV = 4,
} XACT_WAVEBANK_AMBI_CROWD;

#define XACT_WAVEBANK_AMBI_CROWD_ENTRY_COUNT 5

typedef enum
{
    XACT_CUE_A_LP_KM_AT_B_SWING_S = 0,
    XACT_CUE_A_LP_KM_AT_B_SWING_L = 1,
    XACT_CUE_A_LP_KM_AT_B_JUMP_S = 2,
    XACT_CUE_A_LP_KM_AT_B_JUMP_L = 3,
    XACT_CUE_A_LP_KM_AT_B_RUN = 4,
    XACT_CUE_A_LP_KM_AT_B_HORSE = 5,
    XACT_CUE_A_LP_KM_AT_B_ASPH_ORB_S = 6,
    XACT_CUE_A_LP_KM_AT_B_ASPH_ORB_A = 7,
    XACT_CUE_A_LP_KM_B_SOIL_WALK = 8,
    XACT_CUE_A_LP_KM_B_SOIL_RUN = 9,
    XACT_CUE_A_LP_KM_B_SOIL_DOWN_S = 10,
    XACT_CUE_A_LP_KM_B_SOIL_DOWN_L = 11,
    XACT_CUE_A_LP_KM_B_SOIL_LAND = 12,
    XACT_CUE_A_LP_KM_B_SOIL_DASH = 13,
    XACT_CUE_A_LP_KM_B_CLOTH = 14,
    XACT_CUE_A_LP_KM_B_JUMP = 15,
    XACT_CUE_A_LP_KM_B_HORSE_RIDE = 16,
    XACT_CUE_A_LP_KM_B_HORSE_DISMOUNT = 17,
    XACT_CUE_A_LP_KM_B_GUARD = 18,
    XACT_CUE_A_LP_KM_B_AVOID = 19,
    XACT_CUE_A_LP_KM_B_BLOCK_S = 20,
    XACT_CUE_A_LP_KM_AT_B_ASPH_ORB_C = 21,
    XACT_CUE_A_LP_KM_AT_B_ASPH_ORB_SF = 22,
    XACT_CUE_A_LP_KM_B_BLOCK_L = 23,
} XACT_CUE_A_LP_KM;

#define XACT_CUE_A_LP_KM_ENTRY_COUNT 24

typedef enum
{
    XACT_CUE_AMBI_CROWD_CROWD_1000_MEN = 0,
    XACT_CUE_AMBI_CROWD_CROWD_700_MEN = 1,
    XACT_CUE_AMBI_CROWD_CROWD_400_MEN = 2,
    XACT_CUE_AMBI_CROWD_CROWD_100_MEN = 3,
    XACT_CUE_AMBI_CROWD_CROWD_AMBIENCE = 4,
} XACT_CUE_AMBI_CROWD;

#define XACT_CUE_AMBI_CROWD_ENTRY_COUNT 5

#endif // __XACT_PROJECT_NNN_SOUND__
