#pragma once

enum _FC_MENU_PLAYER
{
	_MENU_PLAYER_ALL = -1,

	_MENU_PLAYER_1,
	_MENU_PLAYER_2,
};

enum _FC_MENU_TYPE
{
	_FC_MENU_NONE				= -1,

	_FC_MENU_DEBUG,
	_FC_MENU_MSGBOX,

	//start
	_FC_MENU_LOGO,
	_FC_MENU_OPENING,
	_FC_MENU_TITLE,

	//title
	_FC_MENU_SEL_CHAR,
	_FC_MENU_LOADDATA,
	_FC_MENU_LIBRARY,
	_FC_MENU_OPTION,
	_FC_MENU_CREDITS,
	_FC_MENU_TUTORIAL,

	// mission
	_FC_MENU_SELECT_STAGE,
	_FC_MENU_USUAL,
	_FC_MENU_SAVEDATA,
	_FC_MENU_GUARDIAN,
	
	//library
	_FC_MENU_LIB_CHAR,
		_FC_MENU_LIB_CHAR_SUB,
	_FC_MENU_LIB_MISSION,
		_FC_MENU_LIB_MISSION_SUB,
	_FC_MENU_LIB_ART,
	
	// mission end
	_FC_MENU_GAME_CLEAR,
	_FC_MENU_STAGE_RESULT,
	_FC_MENU_GAME_OVER,
	_FC_MENU_GAME_FAILED,
	_FC_MENU_ADVERTISEMENT_TGS,

	// pause
	_FC_MENU_PAUSE,
	_FC_MENU_STATUS,
	_FC_MENU_ABILITY,
	_FC_MENU_CONTROL,
	_FC_MENU_MISSION_OBJ,

	// Special Sel Stage
	_FC_MENU_SPECIAL_SELSTAGE,

	_FC_MENU_MAX,
};

enum FCMenu_Message
{
	fcMSG_NONE = -1,
	fcMSG_REMOVE_ALL_MENU,
	fcMSG_CLICK_FX_EFFECT,

	// debug menu
	fcMSG_DEBUG_MENU_START,
	fcMSG_DEBUG_MENU_OUT,
	fcMSG_DEBUG_MENU_TOGGLE,			// fantasycore / start call

	// message
	fcMSG_MESSAGEBOX_START,
	fcMSG_MESSAGEBOX_END,

	// main state가 바뀌는 경우.
	fcMSG_GO_TO_LOGO,
	fcMSG_GO_TO_TITLE,
	fcMSG_GO_TO_SEL_STAGE,

	// load후에 world가 바뀌는 경우
	fcMSG_GO_TO_LOAD_SELECT_STAGE,

	// start
	fcMSG_LOGO_START,
	fcMSG_OPENING_START,
	fcMSG_TITLE_START,

	// title
	fcMSG_SEL_CHAR_START,
	fcMSG_FIRST_MISSION_START,
	fcMSG_LOADDATA_START,
	fcMSG_LIBRARY_START,
	fcMSG_OPTION_START,
	fcMSG_CREDITS_START,
	fcMSG_TUTORIAL_START,

	// mission
	fcMSG_SELECT_STAGE_START,
	fcMSG_SELECT_STAGE_TO_MISSION_START,
	fcMSG_USUAL_START,
	fcMSG_USUAL_END,
	fcMSG_USUAL_TO_LOAD_START,
	fcMSG_USUAL_TO_SAVEDATA_START,
	fcMSG_USUAL_TO_OPTION_START,
	fcMSG_SUB_TO_USUAL,
	fcMSG_GUARDIAN_START,
	fcMSG_MISSION_START,
	
	// library
	fcMSG_LIB_CHAR_START,
		fcMSG_LIB_CHAR_SUB_START,
	fcMSG_LIB_MISSION_START,
		fcMSG_LIB_MISSION_SUB_START,
	fcMSG_LIB_ART_START,
		fcMSG_LIB_ART_ILL_START,
		
	// mission end
	fcMSG_GAME_CLEAR_START,
	fcMSG_SUCCESS_REAL_MOVIE_START,
	fcMSG_STAGE_RESULT_START,
	fcMSG_ENDING_CHAR_START,
	fcMSG_END_START,
	fcMSG_SAVEDATA_START,
	fcMSG_GAME_OVER_START,
	fcMSG_GAME_FAILED_START,
	
	// pause
	fcMSG_PAUSE_START,
	fcMSG_PAUSE_FOR_XBOXGUIDE_START,
	fcMSG_PAUSE_END,
	fcMSG_STATUS_START,
	fcMSG_STATUS_END,
	fcMSG_ABILITY_START,
	fcMSG_CONTROL_START,
	fcMSG_MISSION_OBJ_START,
	
	// Special Sel Stage
	fcMSG_SPECIAL_SELSTAGE_START,
	fcMSG_SPECIAL_SELSTAGE_END,
};