#ifndef __BS_TRIGGER_CODE_DEFINE_H__
#define __BS_TRIGGER_CODE_DEFINE_H__

/*
<파라메터 추가 방법> - 새로운 파라메터에 대한 요청이 있는경우
1. BSTriggerCodeDefine.h에 BS_TP_CODE라는 Enum타입에 데이터 추가

2. BSTriggerCodeDefine.h에 TPC로 첫부분이 시작하는 문자열 정의
(이 스트링이 BConditionActionList.cpp에 정의된 파라메터 이름과 같아야 함)

3. BSTriggerDefaultData.cpp에 있는 g_ParamCaptionTable에 1과 2에서
정의한 내용과 함께 마지막 데이터로는 툴에서 쓰이는 파라메터 캡션을 지정해 준다.

4. BSTriggerManager.cpp에 SetSeparateParameter라는 함수에 파라메터 체크 및 형태를 지정해 준다.
※기타 선택시 리스트를 보여줘야 한다던가 하는 특이한 형태의 지정은 BSTriggerContentView.cpp에서 따로 처리해 준다.

<컨디션 추가 방법 - 툴>
1. BSTriggerCodeDefine.h에 BS_CONDITION_ 으로 시작하는 Enum타입에 데이터 추가
2. BSTriggerManager.h에 g_ConditionCodeTable에 1에서 추가한 Enum타입 데이터와 이름이 동일한 문자열 추가

<액션 추가 방법 - 툴>
1. BSTriggerCodeDefine.h에 BS_ACTION_ 으로 시작하는 Enum타입에 데이터 추가
2. BSTriggerManager.h에 g_ActionCodeTable에 1에서 추가한 Enum타입 데이터와 이름이 동일한 문자열 추가
*/



struct BSParamCaptionInfo
{
	int iCodeIndex;
	char szCodeName[128];
	char szCaption[128];
};


enum BS_EVENT_CODE
{
	BTEC_HERO_DIE,
	BTEC_MISSION_END,
	BTEC_LAST,
};

//이벤트 정의
struct BSEventCodeInfo
{
	int  iHandle;
	char szCaption[256];
};

struct BSCodeInfo
{
	int  iHandle;
	char szCodeName[64];
};

enum BS_CONDITION_CODE
{
	CON_INPUTSTICK_A,
	CON_INPUTSTICK_LEFT,
	CON_INPUTSTICK_RIGHT,
	CON_INPUTSTICK_NEUTRAL,
	CON_COMPARE_ORB,
	CON_TIME_ELAPSED,
	CON_TIME_ELAPSED_FROM_MARK,
	CON_TROOP_ATTACKED,
	CON_TROOP_ATTACKED_TROOP,
	CON_COMPARE_TROOP_DIST,
	CON_COMPARE_TROOP_HP,
	CON_TROOP_IN_AREA,
	CON_COMPARE_LEADER_HP,
	CON_TROOP_MELEE_ATTACKED,
	CON_TROOP_RANGE_ATTACKED,
	CON_TROOP_UNBLOCKABLE_ATTACKED,
	CON_TROOP_NO_ENGAGED,
	CON_TROOP_NOT_IN_AREA,
	CON_VAR,
	CON_PROP_WAS_DESTROYED,

	CON_TROOP_ENGAGED,
	CON_FORCE_COMPARE_HP,
	CON_FORCE_ELIMINATED,
	CON_FORCE_IN_AREA,
	CON_FORCE_NOT_IN_AREA,
	CON_FORCE_ALL_IN_AREA,
	CON_PLAYER_GUARDIAN_NUM,

	CON_TROOP_TYPE,
	CON_GUARDIAN_TROOP_TYPE,

	CON_TROOP_LEVEL,

	CON_ORB_GAUGE_FULL,
	CON_TRUE_ORB_GAUGE_FULL,

	CON_TOTAL_KILL_NUM,
	CON_FORCE_KILL_NUM,

	CON_GUARDIAN_IN_AREA,
	CON_GUARDIAN_NOT_IN_AREA,
	CON_GUARDIAN_COMPARE_DIST,
	CON_GUARDIAN_EXIST,
	CON_GUARDIAN_TROOP_TYPE2,

	CON_SELECT_MISION_MENU_VALUE,

	CON_FORCE_COMPARE_UNIT_NUMBER,
	CON_TROOP_COMPARE_UNIT_NUMBER,

	CON_REALMOVIE_FINISH,

	CON_COMPARE_TROOP_N_FORCE_DIST,
	CON_COMPARE_FORCE_N_FORCE_DIST,

	CON_VAR_COMPARE,

	CON_TROOP_ATTACKED_FORCE,
	CON_TROOP_ATTACKED_STR,
	CON_ITEMBOX_BROKEN,

	CON_PROP_HP,
	CON_IS_DEMO_SKIP,

	CON_TROOP_COMPARE_HP_EXCEPT_LEADER,

	CON_LAST,
};

enum BS_ACTION_CODE
{
	ACT_AI_DISABLE,
	ACT_AI_ENABLE,
	ACT_AISET,
	ACT_AISETPATH,
	ACT_BGM_FADE,
	ACT_BGM_MUTE,
	ACT_BGM_PLAY,
	ACT_BGM_STOP,
	ACT_BGM_VOLUME,
	ACT_CAM_RESET,
	ACT_CAM_SET,
	ACT_CAM_TARGETAREA,
	ACT_CAM_TARGETTROOP,
	ACT_DELAY,
	ACT_DEMO_PLAY,
	ACT_EFFECT_FADEIN,
	ACT_EFFECT_FADEINCOLOR,
	ACT_EFFECT_FADEOUT,
	ACT_EFFECT_FADEOUT_COLOR,
	ACT_EFFECT_FOG,
	ACT_EFFECTFX_RANDOM_SET,
	ACT_EFFECTFX_SET,
	ACT_EFFECT_GLOW_OFF,
	ACT_EFFECT_GLOW_ON,
	ACT_EFFECT_LENSFLARE_OFF,
	ACT_EFFECT_LENSFLARE_ON,
	ACT_EFFECT_LIGHT,
	ACT_EFFECT_MOTIONBLUR_OFF,
	ACT_EFFECT_MOTIONBLUR_ON,
	ACT_EFFECT_RAIN_OFF,
	ACT_EFFECT_RAIN_ON,
	ACT_EFFECT_SET_FIRE,
	ACT_EFFECT_SNOW_OFF,
	ACT_EFFECT_SNOW_ON,
	ACT_GATE_CLOSE,
	ACT_GATE_OPEN,
	ACT_HOOK_INPUT_OFF,
	ACT_HOOK_INPUT_ON,
	ACT_INTERFACE_OFF,
	ACT_INTERFACE_ON,
	ACT_LETTER_BOX_OFF,
	ACT_LETTER_BOX_ON,
	ACT_MAP_OFF,
	ACT_MAP_ON,
	ACT_MAP_SCALE,
	ACT_MESSAGE_REPORT,
	ACT_MESSAGE_SAY,
	ACT_MESSAGE_SHOW,
	ACT_MESSAGE_SHOWXY,
	ACT_MISSION_COMPLETED,
	ACT_MISSION_FAILED,
	ACT_ORB_ADD,
	ACT_POINT_AREA_OFF,
	ACT_POINT_AREA_ON,
	ACT_POINT_FRIEND_IN_AREA,
	ACT_POINT_HOSTILE_IN_AREA,
	ACT_POINT_TROOP_OFF,
	ACT_POINT_TROOP_ON,
	ACT_SOUND_SET,
	ACT_SOUND_UNSET,
	ACT_TIME_MARK,
	ACT_TRIGGER_ACTIVATE,
	ACT_TRIGGER_DEACTIVATE,
	ACT_TRIGGER_LOOP,
	ACT_TRIGGER_RESET,
	ACT_TRIGGER_RESETALL,
	ACT_TRIGGER_RESETTHIS,
	ACT_TROOP_ANIMATION,
	ACT_TROOP_ANNIHILATE,
	ACT_TROOP_ATTACK,
	ACT_TROOP_ATTACK_LEADER,
	ACT_TROOP_DISABLE,
	ACT_TROOP_DISABLE_ALL,
	ACT_TROOP_DISABLE_INAREA,
	ACT_TROOP_ENABLE,
	ACT_TROOP_ENABLE_IN_AREA,
	ACT_TROOP_ENEMY_DISABLE_IN_AREA,
	ACT_TROOP_ENEMY_ENABLEINAREA,
	ACT_TROOP_FOLLOW,
	ACT_TROOP_FRIEND_DISABLE_IN_AREA,
	ACT_TROOP_FRIEND_ENABLE_IN_AREA,
	ACT_TROOP_HP_FILL,
	ACT_TROOP_HP_MAX,
	ACT_TROOP_INVULNERABLE,
	ACT_TROOP_LEADER_INVULNERABLE,
	ACT_TROOP_LEADER_VULNERABLE,
	ACT_TROOP_PLACE,
	ACT_TROOP_RANGE_ATTACK_AREA,
	ACT_TROOP_RANGE_ATTACK_WALL,
	ACT_TROOP_RE_NEW,
	ACT_TROOP_RE_NEW_OUTOFSIGHT,
	ACT_TROOP_RUN,
	ACT_TROOP_STOP,
	ACT_TROOP_VULNERABLE,
	ACT_TROOP_WALK,
	ACT_VAR_INCREASE,
	ACT_VAR_SET,
	ACT_WALL_COLLAPSE,
	ACT_WALL_SET_HP,
	ACT_PROP_PUSH,
	ACT_DESTROY_BRIDGE,
	ACT_SET_GUARDIAN_TROOP,
	ACT_SET_ENEMY_ATTR,
	ACT_RESET_ENEMY_ATTR,
	ACT_ENABLE_DYNAMIC_PROP,
	ACT_DISABLE_DYNAMIC_PROP,
	ACT_PLAY_REALTIME_MOVIE,
	ACT_TROOP_HP_GAUGE_SHOW,

	//
	ACT_TROOPTYPE_AI_DISABLE_IN_AREA,
	ACT_TROOPTYPE_AI_ENABLE_IN_AREA,
	ACT_TROOPTYPE_AISET_IN_AREA,
	ACT_TROOPTYPE_ANIMATION_IN_AREA,
	ACT_TROOPTYPE_KILL_ALL_IN_AREA,
	ACT_TROOPTYPE_DISABLE_IN_AREA,
	ACT_TROOPTYPE_HP_FILL_IN_AREA,
	ACT_TROOPTYPE_HP_MAX_IN_AREA,
	ACT_TROOPTYPE_WALK,
	ACT_TROOPTYPE_RUN,
	ACT_TROOPTYPE_STOP_IN_AREA,
	ACT_TROOP_RANGE_ATTACK_TO_AREA,
	ACT_TROOPTYPE_SET_DIRECTION,
	ACT_TROOPTYPE_SHOW_IN_MINIMAP,
	ACT_TROOPTYPE_HIDE_IN_MINIMAP,
	ACT_TROOP_SHOW_IN_MINIMAP,
	ACT_TROOP_HIDE_IN_MINIMAP,
	ACT_UNIT_SHOW_IN_MINIMAP_ON_PROP,
	ACT_UNIT_HIDE_IN_MINIMAP_ON_PROP,

	ACT_PLAYER_ADD_ORB,
	ACT_FORCE_SHOW_HP_GAUGE,
	ACT_FORCE_SHOW_HP_GAUGE_IN_AREA,

	ACT_TROOPS_AI_ENABLE,
	ACT_TROOPS_AI_DISABLE,
	ACT_TROOPS_SET_AI,
	ACT_TROOPS_PLAY_ACTION,
	ACT_TROOPS_ANNIHILATE,
	ACT_TROOPS_DISABLE,
	ACT_TROOPS_HP_FILL,
	ACT_TROOPS_HP_MAX,
	ACT_TROOPS_INVULNERABLE,
	ACT_TROOPS_VULNERABLE,
	ACT_TROOPS_WALK,
	ACT_TROOPS_RUN,
	ACT_TROOPS_STOP,
	ACT_TROOPS_RANGE_ATTACK_AREA,
	ACT_TROOPS_SET_DIR,
	ACT_TROOPS_SHOW_MINIMAP,
	ACT_TROOPS_SHOW_HP_GAUGE,
	ACT_TROOP_CHANGE_GROUP,
	ACT_DYNAMIC_FOG_ENABLE,
	ACT_DYNAMIC_FOG_CROSS,
	ACT_SET_DOF,
	ACT_DISABLE_DOF,
	ACT_DESTROY_CRUMBLE_STONE,
	ACT_DISABLE_DYNAMIC_FOG,
	ACT_SET_PROP_AI_GUIDE,
	ACT_SET_AREA_AI_GUIDE,
	ACT_SET_GUARDIAN_AI,
	ACT_MOVE_MOVETOWER,

	ACT_ADD_OBJECTIVE,
	ACT_REMOVE_OBJECTIVE,
	ACT_CLEAR_OBJECTIVE,

	ACT_DISPLAY_VAR,
	ACT_HIDE_VAR,
	ACT_DISPLAY_VAR_GAUGE,
	ACT_HIDE_VAR_GAUGE,

	ACT_RELEASE_GUARDIAN,

	ACT_SET_VAR_LIVE_TROOP_UNIT_COUNT,
	ACT_SET_VAR_DEAD_TROOP_UNIT_COUNT,
	ACT_SET_VAR_LIVE_FORCE_UNIT_COUNT,
	ACT_SET_VAR_DEAD_FORCE_UNIT_COUNT,

	ACT_PLAY_AMBI_SOUND_ON,
	ACT_PLAY_AMBI_SOUND_OFF,

	ACT_SET_NEXT_STAGE,
	ACT_LINK_ELF_N_DRAGON,

	ACT_SHOW_BOSS_GAUGE,
	ACT_HIDE_BOSS_GAUGE,
	ACT_ADD_TROOP_LIVE_RATE,

	ACT_SET_DYNAMIC_PROP_GROUP_IN_AREA,

	ACT_DROP_ITEM_AT_TROOP_POS,
	ACT_DROP_ITEM_AT_LEADER_POS,
	ACT_DROP_ITEM_IN_AREA,

	ACT_SET_REALTIME_MOVIE_AFTER_MISSION_END,
	ACT_SET_STOP_TRIGGER,

	ACT_TROOPS_ENABLE,
	ACT_CHANGE_TEAM,

	ACT_GUARDIAN_WALK,
	ACT_GUARDIAN_RUN,
	ACT_GUARDIAN_STOP,
	ACT_GUARDIAN_SET_DIR,
	ACT_GUARDIAN_RETREAT,
	ACT_GUARDIAN_AI_SET,

	ACT_TROOP_PICKOUT_ENABLE,

	ACT_GUARDIAN_INC_POWER,
	ACT_GUARDIAN_INC_RANGE, 		

	ACT_TROOP_INC_POWER,		
	ACT_TROOP_INC_RANGE,

	ACT_ENABLE_BLIZZARD_EFFECT,
	ACT_DISABLE_BLIZZARD_EFFECT,

	ACT_SHOW_MISSION_SELECT_MENU,

	ACT_SET_PLAYER_LEVEL_EXP,

	ACT_START_REALTIME_MOVIE,

	ACT_CHANGE_LIGHT,
	ACT_CHANGE_FOG,
	ACT_CHANGE_SCENE,

	ACT_VAR_CLEARTIME,
	ACT_VAR_KILLS,	
	ACT_VAR_NORMALKILLS,
	ACT_VAR_ORBKILLS,
	ACT_VAR_PHYSICSKILLS,
	ACT_VAR_HIGHESTCOMBO,
	ACT_VAR_SUM,
	ACT_VAR_SUB,
	ACT_VAR_MUL,
	ACT_VAR_DIV,
	ACT_VAR_MOD,

	ACT_TROOPS_SET_ATTACKABLE,
	ACT_TRUE_ORB_ADD,
	ACT_TROOP_SET_UNTOUCHABLE,		

	ACT_VAT_CLEARTIME_SCORE,
	ACT_VAR_KILLS_SCORE,
	ACT_VAR_ORBKILLS_SCORE,
	ACT_VAR_HIGHESTCOMBO_SCORE,
	ACT_VAR_SURVIVALRATE_SCORE,
	ACT_VAR_ITEM_SCORE,

	ACT_SET_ADJUTANT_TYPE,

	ACT_ADD_TROOP_EVENT_AREA,
	ACT_SET_TROOP_EVENT_AREA,
	ACT_FORCE_INVULNERABLE,
	ACT_FORCE_VULNERABLE,

	ACT_SET_RESULTRANK,
	ACT_SET_RANKPRIZE,
	ACT_SET_RESULTBONUS,
	ACT_SET_RESULTRANKTABLE,

	ACT_CATAPULT_ATTACK_WALL,
	ACT_SHOW_WALL_HP_GUAGE,

	ACT_SET_TRUEORBENABLE,

	ACT_SHOW_TROOP_GAUGE,
	ACT_HIDE_TROOP_GAUGE,

	ACT_VAR_TOTALUNITS,
	ACT_VAR_ORBSPARKON,
	ACT_PROP_REGEN,

	ACT_TROOP_INC_POWER_SOX,
	ACT_TROOP_INC_RANGE_SOX,
	ACT_TROOP_INC_POWER_SOX_ID,
	ACT_TROOP_INC_RANGE_SOX_ID,	

	ACT_VAR_TOTALUNITS_TEAM,
	ACT_VAR_TROOPHP,

	ACT_DARK_DYNAMIC_FOG_ENABLE,

	ACt_SET_TROOP_FX,

    ACT_CHANGE_SKYBOX,

	ACT_SET_RANKPRIZE_S,
	ACT_SET_RANKPRIZE_A,

	ACT_GUARDIAN_PLACE,

	ACT_SET_ITEMINDEX,
	ACT_VAR_GURADIAN_KILLCOUNT,
	ACT_VAR_GURADIAN_ORB,

	ACT_HIDE_WALL_HP_GUAGE,
	ACT_DARK_DYNAMIC_FOG_ENABLE_EX,
	ACT_DARK_DYNAMIC_FOG_DISABLE_EX,

	ACT_SET_ITEMBOX_ENABLE,
	ACT_SET_ITEMBOX_DISABLE,

	ACT_EFFECT_RAIN_ENABLE,
	ACT_EFFECT_RAIN_DISABLE,

	ACT_SKIP_TEXT,
	ACT_SKIP_REALMOVIE,
	ACT_DELAY_ON_REALMOVIE,

	ACT_SET_WEAPON_FROM_TROOP,
	ACT_SET_TROOP_AI_DISABLE_IN_AREA_FOR_RM,

	ACT_VAR_SCORE_TROOP_HP	,
	ACT_VAR_SCORE_TROOP_TEAM_HP	,
	ACT_VAR_SCORE_TROOP_NUM	,
	ACT_VAR_SCORE_RANGE		,
	ACT_VAR_SCORE_BROKEN_PROP,

	ACT_SET_PROP_CRUSH,

	ACT_SET_CORPSE_DELAY,

	ACT_PLAY_SOUND_EFFECT,
	ACT_ADD_MAXHP,
	ACT_SHOW_TROOP_HP_GAUGE_EXCEPT_LEADER,
	ACT_SET_DEFENSE_REF,
	ACT_SHOW_CIRCLE_AREA_IN_MINIMAP,
	ACT_HIDE_CIRCLE_AREA_IN_MINIMAP,
	ACT_TROOP_ANIMATION_WITH_DELAY,
	ACT_TROOP_DAMAGED_ONLY_PLAYER,
	ACT_ITEM_PROBBT_ADD,

	ACT_VAR_SURVIVALRATE_SCORE_VAR_ARG,
	ACT_VAR_KILLS_SCORE_VAR_ARG,

	ACT_ENABLE_EVENT_TROOP_AI,
	ACT_DISABLE_EVENT_TROOP_AI,

	ACT_POINT_TROOP_STR_ON,
	ACT_POINT_TROOP_STR_OFF,

	ACT_SET_UNIT_AI_ENABLE,
	ACT_SET_UNIT_AI_DISABLE,

	ACT_TROOP_LAST_DISABLE,
	ACT_TROOPS_LAST_DISABLE,

	ACT_VAR_MISSION_LEVEL,

	ACT_VIG_MOTIONBLUR_ENABLE,
	ACT_VIG_MOTIONBLUR_DISABLE,

	ACT_SOUND_SE_PLAYING_OFF,
	ACT_SOUND_SE_PLAYING_ON,

	ACT_LAST,
};

//TPI : Trigger Parameter Index
enum BS_TP_CODE
{

};

//TPC : Trigger Parameter Code
//Parameter name
#define TPC_AREA_ID			"AreaID"
#define TPC_TROOP_ID		"TroopID"
#define TPC_CHAR_ID			"CharID"
#define TPC_INT				"int"
#define TPC_SECONDS			"Seconds"
#define TPC_VARIABLE_ID		"VariableID"
#define TPC_COMPARE			"Compare"
#define TPC_HERO_HP			"HeroHP"
#define	TPC_AI_ID			"AI_ID"
#define TPC_UNIT_AI_ID		"UNIT_AI_ID"
#define TPC_BOSS_AI_ID		"BOSS_AI_ID"
#define TPC_PATH_ID			"PathID"



#define TPC_VARIABLE_NAME  "VariableName"
#define TPC_VARIABLE_TYPE  "VariableType"
#define TPC_VARIABLE_VAL   "VariableVal"
#define TPC_VARIABLE_DESC  "VariableDesc"

#define TPC_TROOP_AI_ID   "TROOP_AI_ID"

#define COMPARE_PARAM_CODE_INDEX	8

#define TROOP_MINE	0
#define TROOP_ENEMY	1
#define TROOP_ALL	2


#endif
