#ifndef __BS_TRIGGER_STR_DEFINITION_H__
#define __BS_TRIGGER_STR_DEFINITION_H__

#define	MAX_BS_TRIGGER_NAME 128
#define	MAX_BS_CODE_NAME	128
#define	MAX_BS_STR_SENTENCE	1024
#define MAX_BS_SHORT_STR	128
#define MAX_BS_TINY_STR		32

#endif