#define SEM_WORLD						"world"
#define SEM_WORLDMATRIXARRAY			"worldmatrixarray"
#define SEM_VIEW						"view"
#define SEM_VIEWINVERSE					"viewinverse"
#define SEM_VIEWINVERSETRANSPOSE		"ViewInverseTranspose"
#define SEM_PROJECTION					"projection"
#define SEM_WORLDVIEW					"worldview"
#define SEM_WORLDVIEWINVERSETRANSPOSE	"worldviewinverseTranspose"
#define SEM_VIEWPROJECTION				"viewprojection"		
#define SEM_WORLDVIEWPROJECTION			"worldviewprojection"
#define SEM_WORLDINVERSETRANSPOSE		"worldinversetranspose"		
#define SEM_LIGHTDIFFUSE				"LightDiffuse"
#define SEM_LIGHTSPECULAR				"LightSpecular"
#define SEM_LIGHTAMBIENT				"LightAmbient"
#define SEM_CAMERAPOSITION				"CameraPosition"			
#define SEM_LIGHTDIRECTION				"Direction"	
#define SEM_VIEW_LIGHTDIRECTION			"LightDirectionViewSpace"
#define SEM_POINTLIGHTNUM					"PointLightNum"
#define SEM_POINTLIGHT_INFO					"PointLightInfo"
#define SEM_POINTLIGHT_COLOR					"PointLightColor"

#define SEM_TIME						"Time"

#define SEM_FOGFACTOR					"FOGFACTOR"
#define SEM_FOGCOLOR					"FOGCOLOR"

#define SEM_SHADOW_ALL					"SHADOW_ALL"
#define SEM_SHADOW_NOWORLD_ALL			"SHADOW_NOWORLD_ALL"
#define SEM_SHADOW_NOVIEW_ALL			"SHADOW_NOVIEW_ALL"
#define SEM_SHADOW_VIEW_LIGHTDIRECTION			"ShadowLightDirectionViewSpace"
#define SEM_SHADOWMAP					"SHADOWMAP"

#define SEM_WORLDLIGHTMAP				"WORLDLIGHTMAP"
#define SEM_RCP_WORLDSIZE				"RcpWorldSize"

#define SEM_SCREENBUFFER				"ScreenBuffer"
#define SEM_REFLECTMAP					"REFLECTMAP"

#define SEM_DEFAULT                     "default"
#define SEM_MATERIALAMBIENT				"MaterialAmbient"
#define SEM_MATERIALDIFFUSE				"MaterialDiffuse"
#define SEM_MATERIALSPECULAR			"MaterialSpecular"
#define SEM_SPECULARPOWER				"SpecularPower"
#define SEM_BUMPPOWER					"BumpPower"
#define SEM_REFLECTPOWER				"ReflectPower"
#define SEM_UVANIMATION_POSITION		"uvanimation_position"	// UV 애니메이션 (fx 에서 사용될 타입명 입니다)
#define SEM_UVANIMATION_ROTATION		"uvanimation_rotation"	
#define SEM_UVANIMATION_SCALE   		"uvanimation_scale"
#define SEM_MORPH_WEIGHT				"morph_weight"
#define SEM_EFFECT_CUSTOM0				"fx_custom0"
#define SEM_EFFECT_CUSTOM1				"fx_custom1"
#define SEM_EFFECT_CUSTOM2				"fx_custom2"
#define SEM_EFFECT_CUSTOM3				"fx_custom3"

#define SEM_NOISEPOWER					"NoisePower"
#define SEM_WATERSPEED				"WaterSpeed"
